/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModelPerformanceRouteImport } from './routes/model-performance'
import { Route as PortfolioAnalyticsRouteImport } from './routes/portfolio-analytics'
import { Route as RiskScoringRouteImport } from './routes/risk-scoring'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelPerformanceRoute = ModelPerformanceRouteImport.update({
  id: '/model-performance',
  path: '/model-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioAnalyticsRoute = PortfolioAnalyticsRouteImport.update({
  id: '/portfolio-analytics',
  path: '/portfolio-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskScoringRoute = RiskScoringRouteImport.update({
  id: '/risk-scoring',
  path: '/risk-scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/portfolio-analytics': typeof PortfolioAnalyticsRoute
  '/risk-scoring': typeof RiskScoringRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/portfolio-analytics': typeof PortfolioAnalyticsRoute
  '/risk-scoring': typeof RiskScoringRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/model-performance': typeof ModelPerformanceRoute
  '/portfolio-analytics': typeof PortfolioAnalyticsRoute
  '/risk-scoring': typeof RiskScoringRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/model-performance'
    | '/portfolio-analytics'
    | '/risk-scoring'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/model-performance'
    | '/portfolio-analytics'
    | '/risk-scoring'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/model-performance'
    | '/portfolio-analytics'
    | '/risk-scoring'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModelPerformanceRoute: typeof ModelPerformanceRoute
  PortfolioAnalyticsRoute: typeof PortfolioAnalyticsRoute
  RiskScoringRoute: typeof RiskScoringRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-performance': {
      id: '/model-performance'
      path: '/model-performance'
      fullPath: '/model-performance'
      preLoaderRoute: typeof ModelPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio-analytics': {
      id: '/portfolio-analytics'
      path: '/portfolio-analytics'
      fullPath: '/portfolio-analytics'
      preLoaderRoute: typeof PortfolioAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-scoring': {
      id: '/risk-scoring'
      path: '/risk-scoring'
      fullPath: '/risk-scoring'
      preLoaderRoute: typeof RiskScoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModelPerformanceRoute: ModelPerformanceRoute,
  PortfolioAnalyticsRoute: PortfolioAnalyticsRoute,
  RiskScoringRoute: RiskScoringRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
